### ISSUE TITLE
Unable to start the docker containers

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [BnademOverflow/FRDP#31]
Hello Yasser,

Thanks for this python API package, it looks really promising.

I was running through the following commands after cloning

```
        make pull
	make build
	make start 
```

Seeing this log on the app frdp container start

```
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

The other services are running and here is the SS of services vs .env file setup.

<img width="485" alt="Screen Shot 2021-12-15 at 3 37 11 AM" src="https://user-images.githubusercontent.com/54947876/146152118-b2ec68e3-9e2c-4c9a-aef5-b5a21cd5d97f.png">

<img width="1161" alt="Screen Shot 2021-12-15 at 3 36 34 AM" src="https://user-images.githubusercontent.com/54947876/146152037-4ee40f43-1e19-4d63-a5ae-362f3fab59db.png">

<img width="785" alt="Screen Shot 2021-12-15 at 3 36 07 AM" src="https://user-images.githubusercontent.com/54947876/146151966-8ecc8a6f-12f8-4955-b5c0-e695c9acc9a5.png">

psql shows the DB list in this way, for the lack of understanding on how to get postgres to work properly am merely looking for some insight. Any help is really appreciate-able.

**Comment by yezz123** [comment]
Let me share my default configuration with you 
```sh
# Backend API
PROJECT_NAME= FRDP
DOMAIN= http://localhost:8080

# openssl rand -hex 32 - Generate secret key
SECRET_KEY= SecretKey
USERS_OPEN_REGISTRATION= true
EMAIL_RESET_TOKEN_EXPIRE_HOURS= 48

# Server Settings
SERVER_NAME= localhost
SERVER_HOST= http://localhost:8080

# Postgres default username and password
POSTGRES_USER= postgres
POSTGRES_PASSWORD= postgres
POSTGRES_DB= frdp
POSTGRES_PORT= 5432
POSTGRES_SERVER= pgdb

# PGADMIN_LISTEN_PORT
PGADMIN_DEFAULT_EMAIL= yezz@localhost.com
PGADMIN_DEFAULT_PASSWORD= postgres
```

I guess the issue is related to the database here or the server of the database we use mostly the name of the Docker container as you see:

```yml
  pgdb:
    image: postgres:12
    container_name: postgres_db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
 ```
we have the pgdb that's why it's would not run for you

**Comment by Elamurugan-Nallathambi** [comment]
Thank you so much for checking my question and sharing this resolution. The following works ok

`.env`

```
# Backend API
PROJECT_NAME=FRDP
DOMAIN=http://localhost:8080

# openssl rand -hex 32 - Generate secret key
SECRET_KEY=SecretKey
USERS_OPEN_REGISTRATION=true
EMAIL_RESET_TOKEN_EXPIRE_HOURS=48

# Server Settings
SERVER_NAME=localhost
SERVER_HOST=http://localhost:8080

# Postgres default username and password
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=frdp
POSTGRES_PORT=5432
POSTGRES_SERVER=pgdb

# PGADMIN_LISTEN_PORT
PGADMIN_DEFAULT_EMAIL=ela@localhost.local
PGADMIN_DEFAULT_PASSWORD=postgres
```

`docker-compose`

```
  pgdb:
    image: postgres:12.9
    container_name: postgres_db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
```

After this update and clearing the previous docker volumes worked ok. 


Only one more question is, `users` table doesn't have entries. If I create a user from postman, that user will became super_user?
